name: todo_caserito
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  quarks_footer:
    git:
      url: https://github.com/Quarks-Studio/quarks_footer.git
      ref: v1.2.0
  firebase_core: ^4.9.0
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/gallery/
    - assets/images/certificates/
